### ISSUE TITLE
やっておくことリストを作る

### ISSUE THREAD

**Issue by kvvzr** [post-internet/onsen-2015-summer#13]
特にハンズオン関係

**Comment by 3846masa** [comment]
WindowsとMacで差異があるから，そこも考慮しておきたい．
環境構築についてだったら，大きく変わらないだろうから，どっかにまとめておきたい

**Comment by mactkg** [comment]
KitematicがWindows版あるので、それが動くなら全部Dockerでくるんだら良いかもしれない。

**Comment by mactkg** [comment]
@kvvzr @3846masa 
post-internet/onsen-2015-summer-textbookとか作りませんか?そこで議論しませんか

**Comment by 3846masa** [comment]
:+1:

**Comment by 3846masa** [comment]
https://github.com/post-internet/onsen-2015-summer-textbook
とりあえずリポジトリ作った
