### ISSUE TITLE
担当者を決める

### ISSUE THREAD

**Issue by kvvzr** [post-internet/onsen-2015-summer#2]
- [x] 幹事長
- [x] 会計
- [x] 合宿幹事
- [x] 配信担当
- [x] サクセソン司会
- [x] ハンズオン司会
- [x] LT司会
- [x] 持ち物担当(配線等)
- [x] 宴会幹事(飲み物、お菓子等の運搬計画も兼ねる)
- [x] タイムキーパー
- [x] 撮影担当

**Comment by kvvzr** [comment]
配信担当は @3846masa と @patchgi です

**Comment by 3846masa** [comment]
なるほど，配信担当やります！

**Comment by kvvzr** [comment]
- [] タイムキーパー

**Comment by kvvzr** [comment]
サクセソン司会 @mactkg 
LT司会 t8m8

**Comment by kvvzr** [comment]
- [ ] 撮影担当

**Comment by kvvzr** [comment]
前回も色々やってくれたし、持ち物担当はとりあえず Korokorotune

**Comment by mactkg** [comment]
@kvvzr korokorotune来なくね?

**Comment by kvvzr** [comment]
ハンズオン司会 @.matatsuna
LTタイムキーパー @.kizaki
お菓子買ってくる担当 @.tako @.wada @.shark
撮影リーダー @.tkd
撮影担当 みんな

**Comment by kvvzr** [comment]
飲み物は近くのスーパーで！
[タイヨー 東庄店](https://www.google.co.jp/maps/place/%EF%BC%88%E6%A0%AA%EF%BC%89%E3%82%BF%E3%82%A4%E3%83%A8%E3%83%BC+%E6%9D%B1%E5%BA%84%E5%BA%97/@35.8447077,140.6539182,17z/data=!3m1!4b1!4m2!3m1!1s0x6022fd0ddb849a41:0x3a4110d2944c4588)
