### ISSUE TITLE
参加者の正式決定

### ISSUE THREAD

**Issue by kvvzr** [post-internet/onsen-2015-summer#3]

**Comment by 3846masa** [comment]
調整さん情報
- mactkg
- 3846masa
- kkrnt
- kwzr
- matatsuna
- kizaki
- huraiboh
- t8m8
- Korokorotune
- たこ
- shark

---

△
- patchgi
- tkd
- 名無し
- たいら

**Comment by kvvzr** [comment]
日程的にはいけるが調整さんに記入していない人
- salmon

たいらくんにはその日大学休みだって教えてあげよう

**Comment by kvvzr** [comment]
名無し is 誰...salmonさんかな...
あとはfrogshisoの返信がない
