### ISSUE TITLE
未成年者の同意書とか不要?

### ISSUE THREAD

**Issue by mactkg** [post-internet/onsen-2015-summer#6]
未成年者が合宿とかに参加する場合、こういう同意書とかを小さいころに書いた覚えがあるのだけれども、不要なんだろか。
ちょっと気になったので書いてみた

http://www.aquarian-age.org/wordpress/wp-content/uploads/pdf/2012_onsen_12.pdf

@kvvzr

**Comment by kvvzr** [comment]
大学が吸収してくれそうな気もするので聞いてみよう

**Comment by kvvzr** [comment]
多分要らない
