### ISSUE TITLE
#rncc夏期講習 ハンズオンの反省を書く

### ISSUE THREAD

**Issue by kvvzr** [post-internet/onsen-2015-summer#7]

**Comment by mactkg** [comment]
- 事前にレジュメを参加者で共有すべし
- サポートの人が必要
  - トラブったりすることがあるけど、同時多発で起きやすいので
  - サポートの人はもちろん一通り通しておくべき
- 最悪GitHubからcloneすれば良いようにしておくと便利だと思う
  - 今回はDockerになるのか?
- npm installなどは要注意
  - とはいえ良い回避策も思いつかないのでうーんという感じがする

**Comment by 3846masa** [comment]
npm install が要注意ってのは，インストールが大変ってこと？
一応あれから調べまして，package.jsonに依存関係出てるので一括インストール可能
package.jsonには，簡単なコマンドを保存できて， `npm run hogehoge`で実行できる
ここを活用すれば，何も考えずに開発環境を提供できるかな？と考えてます

**Comment by 3846masa** [comment]
つまり，ちゃんと準備しましょうってことになりますね，がんばります....

**Comment by mactkg** [comment]
> npm install が要注意ってのは，インストールが大変ってこと？

トラフィックの問題を危惧してました。一気にインストールしようとするので、結構たいへんかもと思って。node_modulesをzipして配布していけるならそれで良い気も。ただnode-gypでbuildするツールもあるはずなので、そういうのがどうなるかは…わかりませんが。

**Comment by 3846masa** [comment]
あーなるほど，確かに....
ちょっと考えてみます... build系が問題だな...
